replicaCount: 1
image:
  repository: ghcr.io/mattjeanes/abyss/abyss.web
  tag: latest@sha256:ffc7e10280c24b4ee675d349e85991d39212d1972e0289c66a5f37be6972a475
  pullPolicy: Always
ingress:
  host: ""
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
env:
  secret:
    Authentication__Discord__ClientSecret: ""
    Authentication__Google__ClientSecret: ""
    Authentication__Steam__ApplicationKey: ""
    Azure__ClientSecret: ""
    Cloudflare__ApiKey: ""
    Ovh__ClientId: ""
    Ovh__ClientSecret: ""
    ConnectionStrings__Abyss: ""
    Discord__Token: ""
    GMod__ApiKey: ""
    Jwt__Key: ""
    Pushover__ApiKey: ""
    Pushover__UserKey: ""
    Tumblr__ConsumerKey: ""
    Tumblr__ConsumerSecret: ""
    Tumblr__Token: ""
    Tumblr__TokenSecret: ""
    WebhookRelay__Relays__GitHub__Key: ""
    WebhookRelay__Relays__GitHub__Urls__0: ""
    WebhookRelay__Relays__GitHub__Urls__1: ""
    WebhookRelay__Relays__GitLab__Key: ""
    WebhookRelay__Relays__GitLab__Urls__0: ""
    WebhookRelay__Relays__GitLab__Urls__1: ""
  normal:
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    Authentication__Discord__ClientId: ""
    Authentication__Google__ClientId: ""
    Azure__ClientId: ""
    Azure__SubscriptionId: ""
    Azure__TenantId: ""
    Cloudflare__Email: ""
    Cloudflare__Zone: ""
    Discord__GuildId: ""
    GMod__BaseUrl: ""
    QuoteOfTheDay__DiscordChannelId: ""
    Reminder__DiscordChannelId: ""
    TeamSpeak__Host: ""
    Tumblr__BlogName: ""
    WhoSaidIt__ModelPath: "/opt/models/whosaidit.zip"
    GPTClient__BaseUrl: ""
